text = input('Write something ')
start_index = int(input('Write start index '))
end_index = int(input('Write end index '))
print('The given text:', text)
print('Start index:', start_index)
print('End index:', end_index)
print('Output string:', text[start_index:end_index])